In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Supply Chain Analytics Dashboard/Dataset/DataCoSupplyChainDataset.csv', encoding="latin1")

In [ ]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Southeast Asia,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,02-03-2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,South Asia,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,South Asia,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Oceania,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Oceania,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 180519
Columns: 48

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Password              180519 non-null  object
 15  Customer Segment               180519 non-null  object
 16  Customer State                 180519 non-null  object
 17  Customer Street                180519 non-null  object
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  object
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  object
 23  Order City                     180519 non-null  object
 24  Order Country                  180519 non-null  object
 25  Order Customer Id              180519 non-null  int64
 26  order date (DateOrders)        180519 non-null  object
 27  Order Id                       180519 non-null  int64
 28  Order Item Cardprod Id         180519 non-null  int64
 29  Order Item Discount            180519 non-null  float64
 30  Order Item Discount Rate       180519 non-null  float64
 31  Order Item Id                  180519 non-null  int64
 32  Order Item Product Price       180519 non-null  float64
 33  Order Item Profit Ratio        180519 non-null  float64
 34  Order Item Quantity            180519 non-null  int64
 35  Sales                          180519 non-null  float64
 36  Order Item Total               180519 non-null  float64
 37  Order Profit Per Order         180519 non-null  float64
 38  Order Region                   180519 non-null  object
 39  Order State                    180519 non-null  object
 40  Order Status                   180519 non-null  object
 41  Product Card Id                180519 non-null  int64
 42  Product Category Id            180519 non-null  int64
 43  Product Image                  180519 non-null  object
 44  Product Name                   180519 non-null  object
 45  Product Price                  180519 non-null  float64
 46  shipping date (DateOrders)     180519 non-null  object
 47  Shipping Mode                  180519 non-null  object
dtypes: float64(12), int64(13), object(23)
memory usage: 66.1+ MB

In [ ]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Department Id,Latitude,Longitude,...,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Card Id,Product Category Id,Product Price
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,5.443460,29.719955,-84.915675,...,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,692.509764,31.851451,141.232550
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,1.629246,9.813646,21.433241,...,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,336.446807,15.640064,139.732492
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,2.000000,-33.937553,-158.025986,...,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,19.000000,2.000000,9.990000
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,4.000000,18.265432,-98.446312,...,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,403.000000,18.000000,50.000000
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,5.000000,33.144863,-76.847908,...,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,627.000000,29.000000,59.990002
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,7.000000,39.279617,-66.370583,...,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,1004.000000,45.000000,199.990005
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,12.000000,48.781933,115.263077,...,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,1363.000000,76.000000,1999.989990

**Data Modeling**

In [ ]:
print("Total Rows:", len(df))

Total Rows: 180519

In [ ]:
print("Unique Order IDs:", df["Order Id"].nunique())

Unique Order IDs: 65752

In [ ]:
print("Unique Order Item IDs:", df["Order Item Id"].nunique())

Unique Order Item IDs: 180519

In [ ]:
print("Unique Customer IDs:", df["Customer Id"].nunique())

Unique Customer IDs: 20652

In [ ]:
print("Unique Product IDs:", df["Product Card Id"].nunique())

Unique Product IDs: 118

In [ ]:
for col in df.columns:
    print(col)

Type
Days for shipping (real)
Days for shipment (scheduled)
Benefit per order
Sales per customer
Delivery Status
Late_delivery_risk
Category Id
Category Name
Customer City
Customer Country
Customer Email
Customer Fname
Customer Id
Customer Password
Customer Segment
Customer State
Customer Street
Department Id
Department Name
Latitude
Longitude
Market
Order City
Order Country
Order Customer Id
order date (DateOrders)
Order Id
Order Item Cardprod Id
Order Item Discount
Order Item Discount Rate
Order Item Id
Order Item Product Price
Order Item Profit Ratio
Order Item Quantity
Sales
Order Item Total
Order Profit Per Order
Order Region
Order State
Order Status
Product Card Id
Product Category Id
Product Image
Product Name
Product Price
shipping date (DateOrders)
Shipping Mode

In [ ]:
columns_to_drop = [
    "Customer Email",
    "Customer Password",
    "Customer Street",
    "Product Image",
    "Order Zipcode",
    "Customer Zipcode"
]

# Drop only if the columns exist
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

print("Remaining columns:", len(df.columns))

Remaining columns: 44

In [ ]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Fname',
 'Customer Id',
 'Customer Segment',
 'Customer State',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Card Id',
 'Product Category Id',
 'Product Name',
 'Product Price',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [ ]:
print((df["Customer Id"] == df["Order Customer Id"]).all())

print((df["Category Id"] == df["Product Category Id"]).all())

print((df["Product Card Id"] == df["Order Item Cardprod Id"]).all())

True
True
True

In [ ]:
df = df.drop(columns=[
    "Order Customer Id",
    "Product Category Id",
    "Order Item Cardprod Id",
    "Sales per customer",
    "Latitude",
    "Longitude"
])

**Normalization**

In [ ]:
customers = df[[
    "Customer Id",
    "Customer Fname",
    "Customer Segment",
    "Customer City",
    "Customer State",
    "Customer Country"
]].drop_duplicates()

In [ ]:
departments = df[[
    "Department Id",
    "Department Name"
]].drop_duplicates()

In [ ]:
products = df[[
    "Product Card Id",
    "Product Name",
    "Product Price",
    "Category Id",
    "Department Id"
]].drop_duplicates()

In [ ]:
categories = df[[
    "Category Id",
    "Category Name"
]].drop_duplicates()

In [ ]:
shipping = df[[
    "Shipping Mode",
    "Delivery Status",
    "Days for shipment (scheduled)",
    "Days for shipping (real)",
    "Late_delivery_risk"
]].drop_duplicates().reset_index(drop=True)

shipping["Shipping ID"] = shipping.index + 1

shipping = shipping[[
    "Shipping ID",
    "Shipping Mode",
    "Delivery Status",
    "Days for shipment (scheduled)",
    "Days for shipping (real)",
    "Late_delivery_risk"
]]

In [ ]:
locations = df[[
    "Market",
    "Order Region",
    "Order Country",
    "Order State",
    "Order City"
]].drop_duplicates().reset_index(drop=True)

locations["Location ID"] = locations.index + 1

locations = locations[[
    "Location ID",
    "Market",
    "Order Region",
    "Order Country",
    "Order State",
    "Order City"
]]

In [ ]:
df = df.merge(
    shipping,
    on=[
        "Shipping Mode",
        "Delivery Status",
        "Days for shipment (scheduled)",
        "Days for shipping (real)",
        "Late_delivery_risk"
    ],
    how="left"
)

In [ ]:
df = df.merge(
    locations,
    on=[
        "Market",
        "Order Region",
        "Order Country",
        "Order State",
        "Order City"
    ],
    how="left"
)

In [ ]:
orders = df[[
    "Order Item Id",
    "Order Id",
    "Customer Id",
    "Product Card Id",
    "Shipping ID",
    "Location ID",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Order Status",
    "Sales",
    "Order Item Quantity",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Total",
    "Benefit per order",
    "Order Profit Per Order",
    "Order Item Profit Ratio"
]]

In [ ]:
dates = pd.DataFrame({
    "Date": pd.concat([
        pd.to_datetime(df["order date (DateOrders)"], format='mixed').dt.date,
        pd.to_datetime(df["shipping date (DateOrders)"], format='mixed').dt.date
    ]).drop_duplicates().sort_values().reset_index(drop=True)
})

dates["Date"] = pd.to_datetime(dates["Date"])

dates["Date ID"] = dates.index + 1
dates["Year"] = dates["Date"].dt.year
dates["Quarter"] = dates["Date"].dt.quarter
dates["Month"] = dates["Date"].dt.month
dates["Month Name"] = dates["Date"].dt.month_name()
dates["Day"] = dates["Date"].dt.day
dates["Day Name"] = dates["Date"].dt.day_name()

dates = dates[[
    "Date ID",
    "Date",
    "Year",
    "Quarter",
    "Month",
    "Month Name",
    "Day",
    "Day Name"
]]

dates.to_csv(output_path + "Date.csv", index=False)

In [ ]:
output_path = "/content/drive/MyDrive/Supply Chain Analytics Dashboard/Data Cleaning & EDA/Normalized Dataset/"

customers.to_csv(output_path + "Customers.csv", index=False)
products.to_csv(output_path + "Products.csv", index=False)
categories.to_csv(output_path + "Categories.csv", index=False)
departments.to_csv(output_path + "Departments.csv", index=False)
shipping.to_csv(output_path + "Shipping.csv", index=False)
locations.to_csv(output_path + "Locations.csv", index=False)
orders.to_csv(output_path + "Orders.csv", index=False)
dates.to_csv(output_path + "Date.csv", index=False)

print("All normalized tables have been saved to Google Drive.")

All normalized tables have been saved to Google Drive.

In [ ]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Categories:", categories.shape)
print("Departments:", departments.shape)
print("Shipping:", shipping.shape)
print("Locations:", locations.shape)
print("Orders:", orders.shape)
print("Date:", dates.shape)

Customers: (20652, 6)
Products: (118, 5)
Categories: (51, 2)
Departments: (11, 2)
Shipping: (26, 6)
Locations: (3772, 6)
Orders: (180519, 17)
Date: (1133, 8)

In [ ]:
shipping = df[[
    "Shipping Mode",
    "Delivery Status",
    "Days for shipment (scheduled)",
    "Days for shipping (real)",
    "Late_delivery_risk"
]].drop_duplicates().reset_index(drop=True)

shipping["Shipping ID"] = range(1, len(shipping) + 1)

shipping = shipping[[
    "Shipping ID",
    "Shipping Mode",
    "Delivery Status",
    "Days for shipment (scheduled)",
    "Days for shipping (real)",
    "Late_delivery_risk"
]]

In [ ]:
locations = df[[
    "Market",
    "Order Region",
    "Order Country",
    "Order State",
    "Order City"
]].drop_duplicates().reset_index(drop=True)

locations["Location ID"] = range(1, len(locations) + 1)

locations = locations[[
    "Location ID",
    "Market",
    "Order Region",
    "Order Country",
    "Order State",
    "Order City"
]]

In [ ]:
df = df.drop(columns=["Shipping ID", "Location ID"], errors="ignore")

In [ ]:
df = df.merge(
    shipping,
    on=[
        "Shipping Mode",
        "Delivery Status",
        "Days for shipment (scheduled)",
        "Days for shipping (real)",
        "Late_delivery_risk"
    ],
    how="left"
)

In [ ]:
df = df.merge(
    locations,
    on=[
        "Market",
        "Order Region",
        "Order Country",
        "Order State",
        "Order City"
    ],
    how="left"
)

In [ ]:
orders = df[[
    "Order Item Id",
    "Order Id",
    "Customer Id",
    "Product Card Id",
    "Shipping ID",
    "Location ID",
    "order date (DateOrders)",
    "shipping date (DateOrders)",
    "Order Status",
    "Sales",
    "Order Item Quantity",
    "Order Item Discount",
    "Order Item Discount Rate",
    "Order Item Total",
    "Benefit per order",
    "Order Profit Per Order",
    "Order Item Profit Ratio"
]]

In [23]:
output_path = "/content/drive/MyDrive/Supply Chain Analytics Dashboard/Data Cleaning & EDA/Normalized Dataset/"
locations.to_csv(output_path + "Locations.csv", index=False)
orders.to_csv(output_path + "Orders.csv", index=False)

In [20]:
output_path = "/content/drive/MyDrive/Supply Chain Analytics Dashboard/Data Cleaning & EDA/Normalized Dataset"

orders.to_csv(output_path + "Orders.csv", index=False)

print("Orders.csv exported successfully.")

Orders.csv exported successfully.

In [22]:
import os

print(os.path.exists(output_path + "Orders.csv"))

True